#!/bin/bash
yum update -y
yum install httpd -y
service httpd start
chkconfig httpd on
cd /var/www/html
echo "<html><h1>Hello Farooq welcome to my webpage<h1></html>" > index.html
aws s3 mb s3://farooqbootstrappingbucket123456
aws s3 cp index.html s3://farooqbootstrappingbucket123456
